### ISSUE TITLE
XML to CSV crash

### ISSUE THREAD

**Issue by philipheinser** [doowb/converter#11]
```
/Users/philip/Desktop/node_modules/converter/src/convert.js:233
        map[self.from][self.to](self.buffer, self.opts, function(err, data) {
                               ^
TypeError: undefined is not a function
    at Transform.self.stream._flush (/Users/philip/Desktop/node_modules/converter/src/convert.js:233:26)
    at Transform.<anonymous> (_stream_transform.js:130:12)
    at Transform.g (events.js:199:16)
    at Transform.emit (events.js:104:17)
    at prefinish (_stream_writable.js:474:12)
    at finishMaybe (_stream_writable.js:482:7)
    at endWritable (_stream_writable.js:493:3)
    at Transform.Writable.end (_stream_writable.js:459:5)
    at ReadStream.onend (_stream_readable.js:505:10)
    at ReadStream.g (events.js:199:16)
```

**Comment by doowb** [comment]
What `options` are you passing into?

This needs more error handling to catch this type of error, thanks for pointing it out.

**Comment by philipheinser** [comment]
```
// setup the options for the data converter
var options = {
    from: 'xml',
    to: 'csv'
};
```

**Comment by doowb** [comment]
Supported conversions can be found in [this map](https://github.com/doowb/converter/blob/master/src/convert.js#L181-L215). We'll get the docs updated and better error handling soon.

**Comment by jonschlinkert** [comment]
fwiw I have an almost complete refactor done
