### ISSUE TITLE
Conversion to YAML seems to be broken

### ISSUE THREAD

**Issue by adius** [doowb/converter#19]
```txt
/project/node_modules/converter/src/convert.js:233
		map[self.from][self.to](self.buffer, self.opts, function(err, data) {
		                       ^

TypeError: map[self.from][self.to] is not a function
    at Transform.Converter.self.stream._flush (/project/node_modules/converter/src/convert.js:233:26)
    at Transform.prefinish (_stream_transform.js:137:10)
    at emitNone (events.js:105:13)
    at Transform.emit (events.js:207:7)
    at prefinish (_stream_writable.js:592:14)
    at finishMaybe (_stream_writable.js:600:5)
    at endWritable (_stream_writable.js:611:3)
    at Transform.Writable.end (_stream_writable.js:562:5)
    at Stringifier.onend (_stream_readable.js:598:10)
    at Object.onceWrapper (events.js:314:30)
```

**Comment by adius** [comment]
Ok seems like you just don't support it yet 😒

**Comment by doowb** [comment]
YAML is supported, but based on #20 you probably used `yaml` instead of `yml`.
